import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Providers from "@/components/provider";
import { TailwindIndicator } from "@/components/tailwind-indicator";

// import { Inter as FontSans } from "next/font/google"

// const fontSans = FontSans({
//   subsets: ["latin"],
//   variable: "--font-sans",
// })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      suppressHydrationWarning
      lang='en'
      className={cn(
        'bg-bgPrimary text-slate-900 antialiased font-poppins',
      )}>
      <head />
      <body>
        <Providers>
          <div >
            {children}
          </div>
        </Providers>
        <TailwindIndicator />
      </body>
    </html>
  );
}
